name: SonarQube Scan
 
on:
  push:
    branches:
      - main
 
jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
 
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'  # Adjust the version as needed
 
      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner
 
      - name: Start SonarScanner
        run:  dotnet sonarscanner begin /k:"SoumyaOrganisation_Org-Repo_5853ccf2-95da-454c-8227-2a40783bf7f4" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="your_sonar_token" /d:sonar.branch.name=main /d:sonar.verbose=true
 
      - name: Build and Test
        run: dotnet build
 
      - name: Finish SonarScanner
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        
